/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsIPDomainWarmupStatus from './ModelsIPDomainWarmupStatus';
import ModelsLabel from './ModelsLabel';
import ModelsSystemDomain from './ModelsSystemDomain';

/**
 * The ModelsIP model module.
 * @module model/ModelsIP
 * @version 1.0.0
 */
class ModelsIP {
    /**
     * Constructs a new <code>ModelsIP</code>.
     * @alias module:model/ModelsIP
     */
    constructor() { 
        
        ModelsIP.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsIP</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsIP} obj Optional instance to populate.
     * @return {module:model/ModelsIP} The populated <code>ModelsIP</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsIP();

            if (data.hasOwnProperty('aolSettings')) {
                obj['aolSettings'] = ApiClient.convertToType(data['aolSettings'], 'String');
            }
            if (data.hasOwnProperty('attSettings')) {
                obj['attSettings'] = ApiClient.convertToType(data['attSettings'], 'String');
            }
            if (data.hasOwnProperty('autoWarmupEnabled')) {
                obj['autoWarmupEnabled'] = ApiClient.convertToType(data['autoWarmupEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('comcastSettings')) {
                obj['comcastSettings'] = ApiClient.convertToType(data['comcastSettings'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('defaultSettings')) {
                obj['defaultSettings'] = ApiClient.convertToType(data['defaultSettings'], 'String');
            }
            if (data.hasOwnProperty('gmailSettings')) {
                obj['gmailSettings'] = ApiClient.convertToType(data['gmailSettings'], 'String');
            }
            if (data.hasOwnProperty('gmxSettings')) {
                obj['gmxSettings'] = ApiClient.convertToType(data['gmxSettings'], 'String');
            }
            if (data.hasOwnProperty('icloudSettings')) {
                obj['icloudSettings'] = ApiClient.convertToType(data['icloudSettings'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('infraClassification')) {
                obj['infraClassification'] = ApiClient.convertToType(data['infraClassification'], 'String');
            }
            if (data.hasOwnProperty('infraMonitor')) {
                obj['infraMonitor'] = ApiClient.convertToType(data['infraMonitor'], 'Boolean');
            }
            if (data.hasOwnProperty('ipDomainWarmupStatus')) {
                obj['ipDomainWarmupStatus'] = ApiClient.convertToType(data['ipDomainWarmupStatus'], [ModelsIPDomainWarmupStatus]);
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], [ModelsLabel]);
            }
            if (data.hasOwnProperty('mailruSettings')) {
                obj['mailruSettings'] = ApiClient.convertToType(data['mailruSettings'], 'String');
            }
            if (data.hasOwnProperty('microsoftSettings')) {
                obj['microsoftSettings'] = ApiClient.convertToType(data['microsoftSettings'], 'String');
            }
            if (data.hasOwnProperty('publicIP')) {
                obj['publicIP'] = ApiClient.convertToType(data['publicIP'], 'String');
            }
            if (data.hasOwnProperty('qqSettings')) {
                obj['qqSettings'] = ApiClient.convertToType(data['qqSettings'], 'String');
            }
            if (data.hasOwnProperty('reverseDNSHostname')) {
                obj['reverseDNSHostname'] = ApiClient.convertToType(data['reverseDNSHostname'], 'String');
            }
            if (data.hasOwnProperty('systemDomain')) {
                obj['systemDomain'] = ModelsSystemDomain.constructFromObject(data['systemDomain']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('yahooSettings')) {
                obj['yahooSettings'] = ApiClient.convertToType(data['yahooSettings'], 'String');
            }
            if (data.hasOwnProperty('yandexSettings')) {
                obj['yandexSettings'] = ApiClient.convertToType(data['yandexSettings'], 'String');
            }
            if (data.hasOwnProperty('zohoSettings')) {
                obj['zohoSettings'] = ApiClient.convertToType(data['zohoSettings'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelsIP</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelsIP</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['aolSettings'] && !(typeof data['aolSettings'] === 'string' || data['aolSettings'] instanceof String)) {
            throw new Error("Expected the field `aolSettings` to be a primitive type in the JSON string but got " + data['aolSettings']);
        }
        // ensure the json data is a string
        if (data['attSettings'] && !(typeof data['attSettings'] === 'string' || data['attSettings'] instanceof String)) {
            throw new Error("Expected the field `attSettings` to be a primitive type in the JSON string but got " + data['attSettings']);
        }
        // ensure the json data is a string
        if (data['comcastSettings'] && !(typeof data['comcastSettings'] === 'string' || data['comcastSettings'] instanceof String)) {
            throw new Error("Expected the field `comcastSettings` to be a primitive type in the JSON string but got " + data['comcastSettings']);
        }
        // ensure the json data is a string
        if (data['defaultSettings'] && !(typeof data['defaultSettings'] === 'string' || data['defaultSettings'] instanceof String)) {
            throw new Error("Expected the field `defaultSettings` to be a primitive type in the JSON string but got " + data['defaultSettings']);
        }
        // ensure the json data is a string
        if (data['gmailSettings'] && !(typeof data['gmailSettings'] === 'string' || data['gmailSettings'] instanceof String)) {
            throw new Error("Expected the field `gmailSettings` to be a primitive type in the JSON string but got " + data['gmailSettings']);
        }
        // ensure the json data is a string
        if (data['gmxSettings'] && !(typeof data['gmxSettings'] === 'string' || data['gmxSettings'] instanceof String)) {
            throw new Error("Expected the field `gmxSettings` to be a primitive type in the JSON string but got " + data['gmxSettings']);
        }
        // ensure the json data is a string
        if (data['icloudSettings'] && !(typeof data['icloudSettings'] === 'string' || data['icloudSettings'] instanceof String)) {
            throw new Error("Expected the field `icloudSettings` to be a primitive type in the JSON string but got " + data['icloudSettings']);
        }
        // ensure the json data is a string
        if (data['infraClassification'] && !(typeof data['infraClassification'] === 'string' || data['infraClassification'] instanceof String)) {
            throw new Error("Expected the field `infraClassification` to be a primitive type in the JSON string but got " + data['infraClassification']);
        }
        if (data['ipDomainWarmupStatus']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ipDomainWarmupStatus'])) {
                throw new Error("Expected the field `ipDomainWarmupStatus` to be an array in the JSON data but got " + data['ipDomainWarmupStatus']);
            }
            // validate the optional field `ipDomainWarmupStatus` (array)
            for (const item of data['ipDomainWarmupStatus']) {
                ModelsIPDomainWarmupStatus.validateJSON(item);
            };
        }
        if (data['labels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['labels'])) {
                throw new Error("Expected the field `labels` to be an array in the JSON data but got " + data['labels']);
            }
            // validate the optional field `labels` (array)
            for (const item of data['labels']) {
                ModelsLabel.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['mailruSettings'] && !(typeof data['mailruSettings'] === 'string' || data['mailruSettings'] instanceof String)) {
            throw new Error("Expected the field `mailruSettings` to be a primitive type in the JSON string but got " + data['mailruSettings']);
        }
        // ensure the json data is a string
        if (data['microsoftSettings'] && !(typeof data['microsoftSettings'] === 'string' || data['microsoftSettings'] instanceof String)) {
            throw new Error("Expected the field `microsoftSettings` to be a primitive type in the JSON string but got " + data['microsoftSettings']);
        }
        // ensure the json data is a string
        if (data['publicIP'] && !(typeof data['publicIP'] === 'string' || data['publicIP'] instanceof String)) {
            throw new Error("Expected the field `publicIP` to be a primitive type in the JSON string but got " + data['publicIP']);
        }
        // ensure the json data is a string
        if (data['qqSettings'] && !(typeof data['qqSettings'] === 'string' || data['qqSettings'] instanceof String)) {
            throw new Error("Expected the field `qqSettings` to be a primitive type in the JSON string but got " + data['qqSettings']);
        }
        // ensure the json data is a string
        if (data['reverseDNSHostname'] && !(typeof data['reverseDNSHostname'] === 'string' || data['reverseDNSHostname'] instanceof String)) {
            throw new Error("Expected the field `reverseDNSHostname` to be a primitive type in the JSON string but got " + data['reverseDNSHostname']);
        }
        // validate the optional field `systemDomain`
        if (data['systemDomain']) { // data not null
          ModelsSystemDomain.validateJSON(data['systemDomain']);
        }
        // ensure the json data is a string
        if (data['yahooSettings'] && !(typeof data['yahooSettings'] === 'string' || data['yahooSettings'] instanceof String)) {
            throw new Error("Expected the field `yahooSettings` to be a primitive type in the JSON string but got " + data['yahooSettings']);
        }
        // ensure the json data is a string
        if (data['yandexSettings'] && !(typeof data['yandexSettings'] === 'string' || data['yandexSettings'] instanceof String)) {
            throw new Error("Expected the field `yandexSettings` to be a primitive type in the JSON string but got " + data['yandexSettings']);
        }
        // ensure the json data is a string
        if (data['zohoSettings'] && !(typeof data['zohoSettings'] === 'string' || data['zohoSettings'] instanceof String)) {
            throw new Error("Expected the field `zohoSettings` to be a primitive type in the JSON string but got " + data['zohoSettings']);
        }

        return true;
    }


}



/**
 * @member {String} aolSettings
 */
ModelsIP.prototype['aolSettings'] = undefined;

/**
 * @member {String} attSettings
 */
ModelsIP.prototype['attSettings'] = undefined;

/**
 * @member {Boolean} autoWarmupEnabled
 */
ModelsIP.prototype['autoWarmupEnabled'] = undefined;

/**
 * @member {String} comcastSettings
 */
ModelsIP.prototype['comcastSettings'] = undefined;

/**
 * @member {Number} created
 */
ModelsIP.prototype['created'] = undefined;

/**
 * @member {String} defaultSettings
 */
ModelsIP.prototype['defaultSettings'] = undefined;

/**
 * @member {String} gmailSettings
 */
ModelsIP.prototype['gmailSettings'] = undefined;

/**
 * @member {String} gmxSettings
 */
ModelsIP.prototype['gmxSettings'] = undefined;

/**
 * @member {String} icloudSettings
 */
ModelsIP.prototype['icloudSettings'] = undefined;

/**
 * @member {Number} id
 */
ModelsIP.prototype['id'] = undefined;

/**
 * @member {String} infraClassification
 */
ModelsIP.prototype['infraClassification'] = undefined;

/**
 * @member {Boolean} infraMonitor
 */
ModelsIP.prototype['infraMonitor'] = undefined;

/**
 * @member {Array.<module:model/ModelsIPDomainWarmupStatus>} ipDomainWarmupStatus
 */
ModelsIP.prototype['ipDomainWarmupStatus'] = undefined;

/**
 * @member {Array.<module:model/ModelsLabel>} labels
 */
ModelsIP.prototype['labels'] = undefined;

/**
 * @member {String} mailruSettings
 */
ModelsIP.prototype['mailruSettings'] = undefined;

/**
 * @member {String} microsoftSettings
 */
ModelsIP.prototype['microsoftSettings'] = undefined;

/**
 * @member {String} publicIP
 */
ModelsIP.prototype['publicIP'] = undefined;

/**
 * @member {String} qqSettings
 */
ModelsIP.prototype['qqSettings'] = undefined;

/**
 * @member {String} reverseDNSHostname
 */
ModelsIP.prototype['reverseDNSHostname'] = undefined;

/**
 * @member {module:model/ModelsSystemDomain} systemDomain
 */
ModelsIP.prototype['systemDomain'] = undefined;

/**
 * @member {Object} type
 */
ModelsIP.prototype['type'] = undefined;

/**
 * @member {String} yahooSettings
 */
ModelsIP.prototype['yahooSettings'] = undefined;

/**
 * @member {String} yandexSettings
 */
ModelsIP.prototype['yandexSettings'] = undefined;

/**
 * @member {String} zohoSettings
 */
ModelsIP.prototype['zohoSettings'] = undefined;






export default ModelsIP;

