/*
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SendPostApi) {
      root.SendPostApi = {};
    }
    root.SendPostApi.ModelsAccountUnlockTicket = factory(root.SendPostApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ModelsAccountUnlockTicket model module.
   * @module model/ModelsAccountUnlockTicket
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsAccountUnlockTicket</code>.
   * @alias module:model/ModelsAccountUnlockTicket
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsAccountUnlockTicket</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsAccountUnlockTicket} obj Optional instance to populate.
   * @return {module:model/ModelsAccountUnlockTicket} The populated <code>ModelsAccountUnlockTicket</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('accountEmail'))
        obj.accountEmail = ApiClient.convertToType(data['accountEmail'], 'String');
      if (data.hasOwnProperty('businessWebURL'))
        obj.businessWebURL = ApiClient.convertToType(data['businessWebURL'], 'String');
      if (data.hasOwnProperty('coldEmails'))
        obj.coldEmails = ApiClient.convertToType(data['coldEmails'], 'String');
      if (data.hasOwnProperty('emailCollection'))
        obj.emailCollection = ApiClient.convertToType(data['emailCollection'], 'String');
      if (data.hasOwnProperty('emailContent'))
        obj.emailContent = ApiClient.convertToType(data['emailContent'], 'String');
      if (data.hasOwnProperty('sendingDomains'))
        obj.sendingDomains = ApiClient.convertToType(data['sendingDomains'], 'String');
      if (data.hasOwnProperty('sendingVolumePerMonth'))
        obj.sendingVolumePerMonth = ApiClient.convertToType(data['sendingVolumePerMonth'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} accountEmail
   */
  exports.prototype.accountEmail = undefined;

  /**
   * @member {String} businessWebURL
   */
  exports.prototype.businessWebURL = undefined;

  /**
   * @member {String} coldEmails
   */
  exports.prototype.coldEmails = undefined;

  /**
   * @member {String} emailCollection
   */
  exports.prototype.emailCollection = undefined;

  /**
   * @member {String} emailContent
   */
  exports.prototype.emailContent = undefined;

  /**
   * @member {String} sendingDomains
   */
  exports.prototype.sendingDomains = undefined;

  /**
   * @member {String} sendingVolumePerMonth
   */
  exports.prototype.sendingVolumePerMonth = undefined;


  return exports;

}));
