/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ModelsDomainCheckResult from '../model/ModelsDomainCheckResult';

/**
* AccountDomainReport service.
* @module api/AccountDomainReportApi
* @version 1.0.0
*/
export default class AccountDomainReportApi {

    /**
    * Constructs a new AccountDomainReportApi. 
    * @alias module:api/AccountDomainReportApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the domainReportRouterReputation operation.
     * @callback module:api/AccountDomainReportApi~domainReportRouterReputationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsDomainCheckResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get reputation of domain
     * @param {String} xAccountApiKey Account API Key
     * @param {Object} opts Optional parameters
     * @param {String} [ip] ip
     * @param {String} [host] host
     * @param {module:api/AccountDomainReportApi~domainReportRouterReputationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsDomainCheckResult}
     */
    domainReportRouterReputation(xAccountApiKey, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling domainReportRouterReputation");
      }

      let pathParams = {
      };
      let queryParams = {
        'ip': opts['ip'],
        'host': opts['host']
      };
      let headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsDomainCheckResult;
      return this.apiClient.callApi(
        '/account/domainReport/reputation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
