/*
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.33
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsAGDomainStat', 'model/ModelsAGIPStat', 'model/ModelsAGSubAccountStat', 'model/ModelsAGTPSPStat', 'model/ModelsAccountCycleUsage', 'model/ModelsCountStat', 'model/ModelsRStat', 'model/ModelsStat'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsAGDomainStat'), require('../model/ModelsAGIPStat'), require('../model/ModelsAGSubAccountStat'), require('../model/ModelsAGTPSPStat'), require('../model/ModelsAccountCycleUsage'), require('../model/ModelsCountStat'), require('../model/ModelsRStat'), require('../model/ModelsStat'));
  } else {
    // Browser globals (root is window)
    if (!root.SendPostApi) {
      root.SendPostApi = {};
    }
    root.SendPostApi.AccountstatApi = factory(root.SendPostApi.ApiClient, root.SendPostApi.ModelsAGDomainStat, root.SendPostApi.ModelsAGIPStat, root.SendPostApi.ModelsAGSubAccountStat, root.SendPostApi.ModelsAGTPSPStat, root.SendPostApi.ModelsAccountCycleUsage, root.SendPostApi.ModelsCountStat, root.SendPostApi.ModelsRStat, root.SendPostApi.ModelsStat);
  }
}(this, function(ApiClient, ModelsAGDomainStat, ModelsAGIPStat, ModelsAGSubAccountStat, ModelsAGTPSPStat, ModelsAccountCycleUsage, ModelsCountStat, ModelsRStat, ModelsStat) {
  'use strict';

  /**
   * Accountstat service.
   * @module api/AccountstatApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AccountstatApi. 
   * @alias module:api/AccountstatApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the accountStatRouterGetAccountCycleUsage operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAccountCycleUsageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsAccountCycleUsage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Responds back with Account Processed Mails Stat <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {module:api/AccountstatApi~accountStatRouterGetAccountCycleUsageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsAccountCycleUsage}
     */
    this.accountStatRouterGetAccountCycleUsage = function(xAccountApiKey, callback) {
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAccountCycleUsage");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsAccountCycleUsage;

      return this.apiClient.callApi(
        '/account/stat/cycleusage', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAccountStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAccountStatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsRStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Account Stats <br>
     * @param {String} xAccountApiKey Sub-Account API Key
     * @param {Object} opts Optional parameters
     * @param {String} opts.from from date
     * @param {String} opts.to to date
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAccountStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsRStat>}
     */
    this.accountStatRouterGetAllAccountStats = function(xAccountApiKey, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAccountStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': opts['from'],
        'to': opts['to'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsRStat];

      return this.apiClient.callApi(
        '/account/stat/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAccountStatsByGroup operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAccountStatsByGroupCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsRStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Account Stats by Group <br>
     * @param {String} xAccountApiKey Sub-Account API Key
     * @param {String} group the group whose stats you want
     * @param {Object} opts Optional parameters
     * @param {String} opts.from from date
     * @param {String} opts.to to date
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAccountStatsByGroupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsRStat>}
     */
    this.accountStatRouterGetAllAccountStatsByGroup = function(xAccountApiKey, group, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAccountStatsByGroup");
      }

      // verify the required parameter 'group' is set
      if (group === undefined || group === null) {
        throw new Error("Missing the required parameter 'group' when calling accountStatRouterGetAllAccountStatsByGroup");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': opts['from'],
        'to': opts['to'],
        'group': group,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsRStat];

      return this.apiClient.callApi(
        '/account/stat/group', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateAccountStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateAccountStatsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Stats <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {Object} opts Optional parameters
     * @param {String} opts.from from date
     * @param {String} opts.to to date
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateAccountStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsStat}
     */
    this.accountStatRouterGetAllAggregateAccountStats = function(xAccountApiKey, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateAccountStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': opts['from'],
        'to': opts['to'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateAccountStatsByGroup operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateAccountStatsByGroupCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Stats by Group <br>
     * @param {String} xAccountApiKey Sub-Account API Key
     * @param {String} group the group whose stats you want
     * @param {Object} opts Optional parameters
     * @param {String} opts.from from date
     * @param {String} opts.to to date
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateAccountStatsByGroupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsStat}
     */
    this.accountStatRouterGetAllAggregateAccountStatsByGroup = function(xAccountApiKey, group, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateAccountStatsByGroup");
      }

      // verify the required parameter 'group' is set
      if (group === undefined || group === null) {
        throw new Error("Missing the required parameter 'group' when calling accountStatRouterGetAllAggregateAccountStatsByGroup");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': opts['from'],
        'to': opts['to'],
        'group': group,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate/group', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateDomainStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateDomainStatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsAGDomainStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Domain Stats <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.orderBy orderBy
     * @param {String} opts.sortOrder sortOrder
     * @param {String} opts.search search term
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.exported exported
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateDomainStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsAGDomainStat>}
     */
    this.accountStatRouterGetAllAggregateDomainStats = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateDomainStats");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateDomainStats");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateDomainStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'orderBy': opts['orderBy'],
        'sortOrder': opts['sortOrder'],
        'search': opts['search'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'exported': opts['exported'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsAGDomainStat];

      return this.apiClient.callApi(
        '/account/stat/aggregate/domain', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateDomainStatsCount operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateDomainStatsCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCountStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Domain Stats Count <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.search search term
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateDomainStatsCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCountStat}
     */
    this.accountStatRouterGetAllAggregateDomainStatsCount = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateDomainStatsCount");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateDomainStatsCount");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateDomainStatsCount");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsCountStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate/domain/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateIPStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateIPStatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsAGIPStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate IP Stats <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.limitBy limitBy
     * @param {Number} opts.limitValue limitValue
     * @param {String} opts.orderBy orderBy
     * @param {String} opts.sortOrder sortOrder
     * @param {String} opts.search search term
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.exported exported
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateIPStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsAGIPStat>}
     */
    this.accountStatRouterGetAllAggregateIPStats = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateIPStats");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateIPStats");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateIPStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'limitBy': opts['limitBy'],
        'limitValue': opts['limitValue'],
        'orderBy': opts['orderBy'],
        'sortOrder': opts['sortOrder'],
        'search': opts['search'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'exported': opts['exported'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsAGIPStat];

      return this.apiClient.callApi(
        '/account/stat/aggregate/ip', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateIPStatsCount operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateIPStatsCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCountStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate IP Stats Count <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.limitBy limitBy
     * @param {Number} opts.limitValue limitValue
     * @param {String} opts.search search term
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateIPStatsCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCountStat}
     */
    this.accountStatRouterGetAllAggregateIPStatsCount = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateIPStatsCount");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateIPStatsCount");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateIPStatsCount");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'limitBy': opts['limitBy'],
        'limitValue': opts['limitValue'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsCountStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate/ip/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateSubAccountStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateSubAccountStatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsAGSubAccountStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate SubAccount Stats <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.orderBy orderBy
     * @param {String} opts.sortOrder sortOrder
     * @param {String} opts.search search term
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.exported exported
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateSubAccountStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsAGSubAccountStat>}
     */
    this.accountStatRouterGetAllAggregateSubAccountStats = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateSubAccountStats");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateSubAccountStats");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateSubAccountStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'orderBy': opts['orderBy'],
        'sortOrder': opts['sortOrder'],
        'search': opts['search'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'exported': opts['exported'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsAGSubAccountStat];

      return this.apiClient.callApi(
        '/account/stat/aggregate/subaccount', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateSubAccountStatsCount operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateSubAccountStatsCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCountStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate SubAccount Stats Count <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.search search term
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateSubAccountStatsCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCountStat}
     */
    this.accountStatRouterGetAllAggregateSubAccountStatsCount = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateSubAccountStatsCount");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateSubAccountStatsCount");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateSubAccountStatsCount");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsCountStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate/subaccount/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateThirdPartyProvidersStats operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateThirdPartyProvidersStatsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsAGTPSPStat>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Third Party Providers Stats <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.orderBy orderBy
     * @param {String} opts.sortOrder sortOrder
     * @param {String} opts.search search term
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.exported exported
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateThirdPartyProvidersStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsAGTPSPStat>}
     */
    this.accountStatRouterGetAllAggregateThirdPartyProvidersStats = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStats");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStats");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStats");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'orderBy': opts['orderBy'],
        'sortOrder': opts['sortOrder'],
        'search': opts['search'],
        'offset': opts['offset'],
        'limit': opts['limit'],
        'exported': opts['exported'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsAGTPSPStat];

      return this.apiClient.callApi(
        '/account/stat/aggregate/tpsp', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the accountStatRouterGetAllAggregateThirdPartyProvidersStatsCount operation.
     * @callback module:api/AccountstatApi~accountStatRouterGetAllAggregateThirdPartyProvidersStatsCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCountStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Aggregate Third Party Providers Stats Count <br>
     * @param {String} xAccountApiKey Account API Key
     * @param {String} from from date
     * @param {String} to to date
     * @param {Object} opts Optional parameters
     * @param {String} opts.filterBy filterBy
     * @param {Number} opts.filterValue filterValue
     * @param {String} opts.search search term
     * @param {module:api/AccountstatApi~accountStatRouterGetAllAggregateThirdPartyProvidersStatsCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCountStat}
     */
    this.accountStatRouterGetAllAggregateThirdPartyProvidersStatsCount = function(xAccountApiKey, from, to, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xAccountApiKey' is set
      if (xAccountApiKey === undefined || xAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xAccountApiKey' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStatsCount");
      }

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStatsCount");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling accountStatRouterGetAllAggregateThirdPartyProvidersStatsCount");
      }


      var pathParams = {
      };
      var queryParams = {
        'from': from,
        'to': to,
        'filterBy': opts['filterBy'],
        'filterValue': opts['filterValue'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Account-ApiKey': xAccountApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsCountStat;

      return this.apiClient.callApi(
        '/account/stat/aggregate/tpsp/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
