/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ModelsCountStat from '../model/ModelsCountStat';
import ModelsDeleteResponse from '../model/ModelsDeleteResponse';
import ModelsESender from '../model/ModelsESender';
import ModelsSender from '../model/ModelsSender';

/**
* SubaccountSender service.
* @module api/SubaccountSenderApi
* @version 1.0.0
*/
export default class SubaccountSenderApi {

    /**
    * Constructs a new SubaccountSenderApi. 
    * @alias module:api/SubaccountSenderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the senderRouterCount operation.
     * @callback module:api/SubaccountSenderApi~senderRouterCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCountStat} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Count Total Senders
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {module:api/SubaccountSenderApi~senderRouterCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCountStat}
     */
    senderRouterCount(xSubAccountApiKey, callback) {
      let postBody = null;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterCount");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsCountStat;
      return this.apiClient.callApi(
        '/subaccount/sender/count', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the senderRouterCreate operation.
     * @callback module:api/SubaccountSenderApi~senderRouterCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsSender} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Sender
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {module:model/ModelsESender} body The Sender content
     * @param {module:api/SubaccountSenderApi~senderRouterCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsSender}
     */
    senderRouterCreate(xSubAccountApiKey, body, callback) {
      let postBody = body;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterCreate");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling senderRouterCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ModelsSender;
      return this.apiClient.callApi(
        '/subaccount/sender/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the senderRouterDelete operation.
     * @callback module:api/SubaccountSenderApi~senderRouterDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsDeleteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Sender
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {Number} senderId The SenderId you want to delete
     * @param {module:api/SubaccountSenderApi~senderRouterDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsDeleteResponse}
     */
    senderRouterDelete(xSubAccountApiKey, senderId, callback) {
      let postBody = null;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterDelete");
      }
      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling senderRouterDelete");
      }

      let pathParams = {
        'senderId': senderId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsDeleteResponse;
      return this.apiClient.callApi(
        '/subaccount/sender/{senderId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the senderRouterGet operation.
     * @callback module:api/SubaccountSenderApi~senderRouterGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsSender} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find Sender by SenderId
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {Number} senderId the SenderId you want to get
     * @param {module:api/SubaccountSenderApi~senderRouterGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsSender}
     */
    senderRouterGet(xSubAccountApiKey, senderId, callback) {
      let postBody = null;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterGet");
      }
      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling senderRouterGet");
      }

      let pathParams = {
        'senderId': senderId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsSender;
      return this.apiClient.callApi(
        '/subaccount/sender/{senderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the senderRouterGetAll operation.
     * @callback module:api/SubaccountSenderApi~senderRouterGetAllCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsSender>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Senders
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {Object} opts Optional parameters
     * @param {Number} [offset] offset
     * @param {Number} [limit] limit
     * @param {String} [search] search term
     * @param {module:api/SubaccountSenderApi~senderRouterGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsSender>}
     */
    senderRouterGetAll(xSubAccountApiKey, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterGetAll");
      }

      let pathParams = {
      };
      let queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit'],
        'search': opts['search']
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelsSender];
      return this.apiClient.callApi(
        '/subaccount/sender/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the senderRouterUpdate operation.
     * @callback module:api/SubaccountSenderApi~senderRouterUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsSender} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Sender
     * @param {String} xSubAccountApiKey Sub-Account API Key
     * @param {Number} senderId The SenderId you want to update
     * @param {module:model/ModelsESender} body The body
     * @param {module:api/SubaccountSenderApi~senderRouterUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsSender}
     */
    senderRouterUpdate(xSubAccountApiKey, senderId, body, callback) {
      let postBody = body;
      // verify the required parameter 'xSubAccountApiKey' is set
      if (xSubAccountApiKey === undefined || xSubAccountApiKey === null) {
        throw new Error("Missing the required parameter 'xSubAccountApiKey' when calling senderRouterUpdate");
      }
      // verify the required parameter 'senderId' is set
      if (senderId === undefined || senderId === null) {
        throw new Error("Missing the required parameter 'senderId' when calling senderRouterUpdate");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling senderRouterUpdate");
      }

      let pathParams = {
        'senderId': senderId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-SubAccount-ApiKey': xSubAccountApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ModelsSender;
      return this.apiClient.callApi(
        '/subaccount/sender/{senderId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
