/*
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendPostApi);
  }
}(this, function(expect, SendPostApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsCertificateDetails', function() {
      beforeEach(function() {
        instance = new SendPostApi.ModelsCertificateDetails();
      });

      it('should create an instance of ModelsCertificateDetails', function() {
        // TODO: update the code to test ModelsCertificateDetails
        expect(instance).to.be.a(SendPostApi.ModelsCertificateDetails);
      });

      it('should have the property extensions (base name: "extensions")', function() {
        // TODO: update the code to test the property extensions
        expect(instance).to.have.property('extensions');
        // expect(instance.extensions).to.be(expectedValueLiteral);
      });

      it('should have the property issuer (base name: "issuer")', function() {
        // TODO: update the code to test the property issuer
        expect(instance).to.have.property('issuer');
        // expect(instance.issuer).to.be(expectedValueLiteral);
      });

      it('should have the property signature (base name: "signature")', function() {
        // TODO: update the code to test the property signature
        expect(instance).to.have.property('signature');
        // expect(instance.signature).to.be(expectedValueLiteral);
      });

      it('should have the property subject (base name: "subject")', function() {
        // TODO: update the code to test the property subject
        expect(instance).to.have.property('subject');
        // expect(instance.subject).to.be(expectedValueLiteral);
      });

      it('should have the property validity (base name: "validity")', function() {
        // TODO: update the code to test the property validity
        expect(instance).to.have.property('validity');
        // expect(instance.validity).to.be(expectedValueLiteral);
      });

    });
  });

}));
