/**
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ModelsAGDomainStat from './model/ModelsAGDomainStat';
import ModelsAGIPStat from './model/ModelsAGIPStat';
import ModelsAGStat from './model/ModelsAGStat';
import ModelsAGSubAccountStat from './model/ModelsAGSubAccountStat';
import ModelsAGTPSPStat from './model/ModelsAGTPSPStat';
import ModelsAIPStat from './model/ModelsAIPStat';
import ModelsAPStat from './model/ModelsAPStat';
import ModelsASStat from './model/ModelsASStat';
import ModelsAccount from './model/ModelsAccount';
import ModelsAccountCycleUsage from './model/ModelsAccountCycleUsage';
import ModelsAccountDomain from './model/ModelsAccountDomain';
import ModelsAccountIPPool from './model/ModelsAccountIPPool';
import ModelsAccountTemplate from './model/ModelsAccountTemplate';
import ModelsAccountUnlockTicket from './model/ModelsAccountUnlockTicket';
import ModelsAccountWebhook from './model/ModelsAccountWebhook';
import ModelsAlertRequest from './model/ModelsAlertRequest';
import ModelsAlertResponse from './model/ModelsAlertResponse';
import ModelsAllClusterCache from './model/ModelsAllClusterCache';
import ModelsAttachment from './model/ModelsAttachment';
import ModelsAuthInfo from './model/ModelsAuthInfo';
import ModelsAutoWarmupContent from './model/ModelsAutoWarmupContent';
import ModelsAutoWarmupContentRequest from './model/ModelsAutoWarmupContentRequest';
import ModelsAutoWarmupDailySchedule from './model/ModelsAutoWarmupDailySchedule';
import ModelsAutoWarmupDomainSchedule from './model/ModelsAutoWarmupDomainSchedule';
import ModelsAutoWarmupPlan from './model/ModelsAutoWarmupPlan';
import ModelsAutoWarmupPlanRequest from './model/ModelsAutoWarmupPlanRequest';
import ModelsAutoWarmupRecipient from './model/ModelsAutoWarmupRecipient';
import ModelsAutoWarmupRecipientResponse from './model/ModelsAutoWarmupRecipientResponse';
import ModelsBackOffConfiguration from './model/ModelsBackOffConfiguration';
import ModelsBackOffTrigger from './model/ModelsBackOffTrigger';
import ModelsBillingPortalSession from './model/ModelsBillingPortalSession';
import ModelsBlackListEngine from './model/ModelsBlackListEngine';
import ModelsBlackListResult from './model/ModelsBlackListResult';
import ModelsBlacklistResource from './model/ModelsBlacklistResource';
import ModelsBlacklistedOn from './model/ModelsBlacklistedOn';
import ModelsBulkResponse from './model/ModelsBulkResponse';
import ModelsCertificateDetails from './model/ModelsCertificateDetails';
import ModelsCertificateExtensions from './model/ModelsCertificateExtensions';
import ModelsCertificateIssuer from './model/ModelsCertificateIssuer';
import ModelsCertificateSignature from './model/ModelsCertificateSignature';
import ModelsCertificateSubject from './model/ModelsCertificateSubject';
import ModelsCertificateValidity from './model/ModelsCertificateValidity';
import ModelsCity from './model/ModelsCity';
import ModelsCleanedList from './model/ModelsCleanedList';
import ModelsClusterCache from './model/ModelsClusterCache';
import ModelsComment from './model/ModelsComment';
import ModelsConsumerStats from './model/ModelsConsumerStats';
import ModelsContent from './model/ModelsContent';
import ModelsCopyTo from './model/ModelsCopyTo';
import ModelsCountStat from './model/ModelsCountStat';
import ModelsCountry from './model/ModelsCountry';
import ModelsCoupon from './model/ModelsCoupon';
import ModelsCouponOptions from './model/ModelsCouponOptions';
import ModelsCreateMailReport from './model/ModelsCreateMailReport';
import ModelsDNSRecord from './model/ModelsDNSRecord';
import ModelsDedicatedIPs from './model/ModelsDedicatedIPs';
import ModelsDeleteResponse from './model/ModelsDeleteResponse';
import ModelsDetailedAlert from './model/ModelsDetailedAlert';
import ModelsDomain from './model/ModelsDomain';
import ModelsDomainAge from './model/ModelsDomainAge';
import ModelsDomainCheckResult from './model/ModelsDomainCheckResult';
import ModelsEAccount from './model/ModelsEAccount';
import ModelsEAccountMember from './model/ModelsEAccountMember';
import ModelsEAccountSetting from './model/ModelsEAccountSetting';
import ModelsEAlert from './model/ModelsEAlert';
import ModelsEComment from './model/ModelsEComment';
import ModelsEDomain from './model/ModelsEDomain';
import ModelsEIP from './model/ModelsEIP';
import ModelsEIPPool from './model/ModelsEIPPool';
import ModelsEIncident from './model/ModelsEIncident';
import ModelsEIntegration from './model/ModelsEIntegration';
import ModelsEInvitation from './model/ModelsEInvitation';
import ModelsEMember from './model/ModelsEMember';
import ModelsESender from './model/ModelsESender';
import ModelsESubAccount from './model/ModelsESubAccount';
import ModelsESystemDomain from './model/ModelsESystemDomain';
import ModelsEThirdPartySendingProvider from './model/ModelsEThirdPartySendingProvider';
import ModelsEWebhook from './model/ModelsEWebhook';
import ModelsEditorTokenResponse from './model/ModelsEditorTokenResponse';
import ModelsEmailList from './model/ModelsEmailList';
import ModelsEmailMessage from './model/ModelsEmailMessage';
import ModelsEmailResponse from './model/ModelsEmailResponse';
import ModelsEventMetadata from './model/ModelsEventMetadata';
import ModelsFrom from './model/ModelsFrom';
import ModelsHetrixtoolsBlacklist from './model/ModelsHetrixtoolsBlacklist';
import ModelsHetrixtoolsMonitorStat from './model/ModelsHetrixtoolsMonitorStat';
import ModelsIEIP from './model/ModelsIEIP';
import ModelsIEMember from './model/ModelsIEMember';
import ModelsIESubAccount from './model/ModelsIESubAccount';
import ModelsIETag from './model/ModelsIETag';
import ModelsIIP from './model/ModelsIIP';
import ModelsIP from './model/ModelsIP';
import ModelsIPDomainWarmupStatus from './model/ModelsIPDomainWarmupStatus';
import ModelsIPHealthResponse from './model/ModelsIPHealthResponse';
import ModelsIPPool from './model/ModelsIPPool';
import ModelsIPProviderSettings from './model/ModelsIPProviderSettings';
import ModelsIPStat from './model/ModelsIPStat';
import ModelsIncident from './model/ModelsIncident';
import ModelsInstance from './model/ModelsInstance';
import ModelsIntegration from './model/ModelsIntegration';
import ModelsIntegrationSettings from './model/ModelsIntegrationSettings';
import ModelsInvitation from './model/ModelsInvitation';
import ModelsLabel from './model/ModelsLabel';
import ModelsLinks from './model/ModelsLinks';
import ModelsMailReportResult from './model/ModelsMailReportResult';
import ModelsMailgunClientInfo from './model/ModelsMailgunClientInfo';
import ModelsMailgunDeliveryStatus from './model/ModelsMailgunDeliveryStatus';
import ModelsMailgunEvent from './model/ModelsMailgunEvent';
import ModelsMailgunMessage from './model/ModelsMailgunMessage';
import ModelsMailgunSignature from './model/ModelsMailgunSignature';
import ModelsMailgunUserVariables from './model/ModelsMailgunUserVariables';
import ModelsMember from './model/ModelsMember';
import ModelsOnboardingChecklist from './model/ModelsOnboardingChecklist';
import ModelsPDStat from './model/ModelsPDStat';
import ModelsPaymentAddress from './model/ModelsPaymentAddress';
import ModelsPaymentOptions from './model/ModelsPaymentOptions';
import ModelsPaymentStatus from './model/ModelsPaymentStatus';
import ModelsPostmasterDomainStat from './model/ModelsPostmasterDomainStat';
import ModelsPricing from './model/ModelsPricing';
import ModelsProvider from './model/ModelsProvider';
import ModelsProviderDetails from './model/ModelsProviderDetails';
import ModelsProviderResult from './model/ModelsProviderResult';
import ModelsProviderSettings from './model/ModelsProviderSettings';
import ModelsQEmailMessage from './model/ModelsQEmailMessage';
import ModelsQEvent from './model/ModelsQEvent';
import ModelsRAssumeAccount from './model/ModelsRAssumeAccount';
import ModelsRDStat from './model/ModelsRDStat';
import ModelsRDSuppression from './model/ModelsRDSuppression';
import ModelsRHetrixtoolsMonitorStat from './model/ModelsRHetrixtoolsMonitorStat';
import ModelsRIPStat from './model/ModelsRIPStat';
import ModelsRStat from './model/ModelsRStat';
import ModelsRSuppression from './model/ModelsRSuppression';
import ModelsReplyTo from './model/ModelsReplyTo';
import ModelsReportProvider from './model/ModelsReportProvider';
import ModelsResponse from './model/ModelsResponse';
import ModelsSDStat from './model/ModelsSDStat';
import ModelsSMTPAuth from './model/ModelsSMTPAuth';
import ModelsSMTPStat from './model/ModelsSMTPStat';
import ModelsSSLCertificate from './model/ModelsSSLCertificate';
import ModelsSSLInfo from './model/ModelsSSLInfo';
import ModelsSender from './model/ModelsSender';
import ModelsSendgridEvent from './model/ModelsSendgridEvent';
import ModelsSingleCleanedMail from './model/ModelsSingleCleanedMail';
import ModelsStat from './model/ModelsStat';
import ModelsSubAccount from './model/ModelsSubAccount';
import ModelsSuppression from './model/ModelsSuppression';
import ModelsSuppressionEmail from './model/ModelsSuppressionEmail';
import ModelsSystemDNSRecord from './model/ModelsSystemDNSRecord';
import ModelsSystemDomain from './model/ModelsSystemDomain';
import ModelsSystemIPPool from './model/ModelsSystemIPPool';
import ModelsSystemTemplate from './model/ModelsSystemTemplate';
import ModelsTag from './model/ModelsTag';
import ModelsTaxDetails from './model/ModelsTaxDetails';
import ModelsThirdPartySendingProvider from './model/ModelsThirdPartySendingProvider';
import ModelsTo from './model/ModelsTo';
import ModelsValidation from './model/ModelsValidation';
import ModelsVerifyByMemberTokenRequest from './model/ModelsVerifyByMemberTokenRequest';
import ModelsVerifyByTokenRequest from './model/ModelsVerifyByTokenRequest';
import ModelsWMessage from './model/ModelsWMessage';
import UaparserDevice from './model/UaparserDevice';
import UaparserOs from './model/UaparserOs';
import UaparserUserAgent from './model/UaparserUserAgent';
import AccountAdminApi from './api/AccountAdminApi';
import AccountAlertApi from './api/AccountAlertApi';
import AccountDomainApi from './api/AccountDomainApi';
import AccountDomainReportApi from './api/AccountDomainReportApi';
import AccountDomainStatApi from './api/AccountDomainStatApi';
import AccountEventApi from './api/AccountEventApi';
import AccountIncidentApi from './api/AccountIncidentApi';
import AccountIntegrationApi from './api/AccountIntegrationApi';
import AccountInvitationApi from './api/AccountInvitationApi';
import AccountIpApi from './api/AccountIpApi';
import AccountIpStatApi from './api/AccountIpStatApi';
import AccountIppoolApi from './api/AccountIppoolApi';
import AccountLabelApi from './api/AccountLabelApi';
import AccountMailReportApi from './api/AccountMailReportApi';
import AccountMemberApi from './api/AccountMemberApi';
import AccountMessageApi from './api/AccountMessageApi';
import AccountOnboardingApi from './api/AccountOnboardingApi';
import AccountPaymentApi from './api/AccountPaymentApi';
import AccountRecipientApi from './api/AccountRecipientApi';
import AccountSettingApi from './api/AccountSettingApi';
import AccountSmtpStatApi from './api/AccountSmtpStatApi';
import AccountStatApi from './api/AccountStatApi';
import AccountSubaccountApi from './api/AccountSubaccountApi';
import AccountSubaccountStatApi from './api/AccountSubaccountStatApi';
import AccountTagApi from './api/AccountTagApi';
import AccountTemplateApi from './api/AccountTemplateApi';
import AccountTpspApi from './api/AccountTpspApi';
import AccountTpspStatApi from './api/AccountTpspStatApi';
import AccountValidationApi from './api/AccountValidationApi';
import AccountWebhookApi from './api/AccountWebhookApi';
import AuthApi from './api/AuthApi';
import ClusterApi from './api/ClusterApi';
import EditorApi from './api/EditorApi';
import SmtpApi from './api/SmtpApi';
import SubaccountDomainApi from './api/SubaccountDomainApi';
import SubaccountEmailApi from './api/SubaccountEmailApi';
import SubaccountIppoolApi from './api/SubaccountIppoolApi';
import SubaccountSenderApi from './api/SubaccountSenderApi';
import SubaccountSuppressionApi from './api/SubaccountSuppressionApi';
import SystemSuppressionApi from './api/SystemSuppressionApi';
import SystemTemplateApi from './api/SystemTemplateApi';
import TrackApi from './api/TrackApi';


/**
* Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SendPostApi = require('index'); // See note below*.
* var xxxSvc = new SendPostApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SendPostApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SendPostApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SendPostApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ModelsAGDomainStat model constructor.
     * @property {module:model/ModelsAGDomainStat}
     */
    ModelsAGDomainStat,

    /**
     * The ModelsAGIPStat model constructor.
     * @property {module:model/ModelsAGIPStat}
     */
    ModelsAGIPStat,

    /**
     * The ModelsAGStat model constructor.
     * @property {module:model/ModelsAGStat}
     */
    ModelsAGStat,

    /**
     * The ModelsAGSubAccountStat model constructor.
     * @property {module:model/ModelsAGSubAccountStat}
     */
    ModelsAGSubAccountStat,

    /**
     * The ModelsAGTPSPStat model constructor.
     * @property {module:model/ModelsAGTPSPStat}
     */
    ModelsAGTPSPStat,

    /**
     * The ModelsAIPStat model constructor.
     * @property {module:model/ModelsAIPStat}
     */
    ModelsAIPStat,

    /**
     * The ModelsAPStat model constructor.
     * @property {module:model/ModelsAPStat}
     */
    ModelsAPStat,

    /**
     * The ModelsASStat model constructor.
     * @property {module:model/ModelsASStat}
     */
    ModelsASStat,

    /**
     * The ModelsAccount model constructor.
     * @property {module:model/ModelsAccount}
     */
    ModelsAccount,

    /**
     * The ModelsAccountCycleUsage model constructor.
     * @property {module:model/ModelsAccountCycleUsage}
     */
    ModelsAccountCycleUsage,

    /**
     * The ModelsAccountDomain model constructor.
     * @property {module:model/ModelsAccountDomain}
     */
    ModelsAccountDomain,

    /**
     * The ModelsAccountIPPool model constructor.
     * @property {module:model/ModelsAccountIPPool}
     */
    ModelsAccountIPPool,

    /**
     * The ModelsAccountTemplate model constructor.
     * @property {module:model/ModelsAccountTemplate}
     */
    ModelsAccountTemplate,

    /**
     * The ModelsAccountUnlockTicket model constructor.
     * @property {module:model/ModelsAccountUnlockTicket}
     */
    ModelsAccountUnlockTicket,

    /**
     * The ModelsAccountWebhook model constructor.
     * @property {module:model/ModelsAccountWebhook}
     */
    ModelsAccountWebhook,

    /**
     * The ModelsAlertRequest model constructor.
     * @property {module:model/ModelsAlertRequest}
     */
    ModelsAlertRequest,

    /**
     * The ModelsAlertResponse model constructor.
     * @property {module:model/ModelsAlertResponse}
     */
    ModelsAlertResponse,

    /**
     * The ModelsAllClusterCache model constructor.
     * @property {module:model/ModelsAllClusterCache}
     */
    ModelsAllClusterCache,

    /**
     * The ModelsAttachment model constructor.
     * @property {module:model/ModelsAttachment}
     */
    ModelsAttachment,

    /**
     * The ModelsAuthInfo model constructor.
     * @property {module:model/ModelsAuthInfo}
     */
    ModelsAuthInfo,

    /**
     * The ModelsAutoWarmupContent model constructor.
     * @property {module:model/ModelsAutoWarmupContent}
     */
    ModelsAutoWarmupContent,

    /**
     * The ModelsAutoWarmupContentRequest model constructor.
     * @property {module:model/ModelsAutoWarmupContentRequest}
     */
    ModelsAutoWarmupContentRequest,

    /**
     * The ModelsAutoWarmupDailySchedule model constructor.
     * @property {module:model/ModelsAutoWarmupDailySchedule}
     */
    ModelsAutoWarmupDailySchedule,

    /**
     * The ModelsAutoWarmupDomainSchedule model constructor.
     * @property {module:model/ModelsAutoWarmupDomainSchedule}
     */
    ModelsAutoWarmupDomainSchedule,

    /**
     * The ModelsAutoWarmupPlan model constructor.
     * @property {module:model/ModelsAutoWarmupPlan}
     */
    ModelsAutoWarmupPlan,

    /**
     * The ModelsAutoWarmupPlanRequest model constructor.
     * @property {module:model/ModelsAutoWarmupPlanRequest}
     */
    ModelsAutoWarmupPlanRequest,

    /**
     * The ModelsAutoWarmupRecipient model constructor.
     * @property {module:model/ModelsAutoWarmupRecipient}
     */
    ModelsAutoWarmupRecipient,

    /**
     * The ModelsAutoWarmupRecipientResponse model constructor.
     * @property {module:model/ModelsAutoWarmupRecipientResponse}
     */
    ModelsAutoWarmupRecipientResponse,

    /**
     * The ModelsBackOffConfiguration model constructor.
     * @property {module:model/ModelsBackOffConfiguration}
     */
    ModelsBackOffConfiguration,

    /**
     * The ModelsBackOffTrigger model constructor.
     * @property {module:model/ModelsBackOffTrigger}
     */
    ModelsBackOffTrigger,

    /**
     * The ModelsBillingPortalSession model constructor.
     * @property {module:model/ModelsBillingPortalSession}
     */
    ModelsBillingPortalSession,

    /**
     * The ModelsBlackListEngine model constructor.
     * @property {module:model/ModelsBlackListEngine}
     */
    ModelsBlackListEngine,

    /**
     * The ModelsBlackListResult model constructor.
     * @property {module:model/ModelsBlackListResult}
     */
    ModelsBlackListResult,

    /**
     * The ModelsBlacklistResource model constructor.
     * @property {module:model/ModelsBlacklistResource}
     */
    ModelsBlacklistResource,

    /**
     * The ModelsBlacklistedOn model constructor.
     * @property {module:model/ModelsBlacklistedOn}
     */
    ModelsBlacklistedOn,

    /**
     * The ModelsBulkResponse model constructor.
     * @property {module:model/ModelsBulkResponse}
     */
    ModelsBulkResponse,

    /**
     * The ModelsCertificateDetails model constructor.
     * @property {module:model/ModelsCertificateDetails}
     */
    ModelsCertificateDetails,

    /**
     * The ModelsCertificateExtensions model constructor.
     * @property {module:model/ModelsCertificateExtensions}
     */
    ModelsCertificateExtensions,

    /**
     * The ModelsCertificateIssuer model constructor.
     * @property {module:model/ModelsCertificateIssuer}
     */
    ModelsCertificateIssuer,

    /**
     * The ModelsCertificateSignature model constructor.
     * @property {module:model/ModelsCertificateSignature}
     */
    ModelsCertificateSignature,

    /**
     * The ModelsCertificateSubject model constructor.
     * @property {module:model/ModelsCertificateSubject}
     */
    ModelsCertificateSubject,

    /**
     * The ModelsCertificateValidity model constructor.
     * @property {module:model/ModelsCertificateValidity}
     */
    ModelsCertificateValidity,

    /**
     * The ModelsCity model constructor.
     * @property {module:model/ModelsCity}
     */
    ModelsCity,

    /**
     * The ModelsCleanedList model constructor.
     * @property {module:model/ModelsCleanedList}
     */
    ModelsCleanedList,

    /**
     * The ModelsClusterCache model constructor.
     * @property {module:model/ModelsClusterCache}
     */
    ModelsClusterCache,

    /**
     * The ModelsComment model constructor.
     * @property {module:model/ModelsComment}
     */
    ModelsComment,

    /**
     * The ModelsConsumerStats model constructor.
     * @property {module:model/ModelsConsumerStats}
     */
    ModelsConsumerStats,

    /**
     * The ModelsContent model constructor.
     * @property {module:model/ModelsContent}
     */
    ModelsContent,

    /**
     * The ModelsCopyTo model constructor.
     * @property {module:model/ModelsCopyTo}
     */
    ModelsCopyTo,

    /**
     * The ModelsCountStat model constructor.
     * @property {module:model/ModelsCountStat}
     */
    ModelsCountStat,

    /**
     * The ModelsCountry model constructor.
     * @property {module:model/ModelsCountry}
     */
    ModelsCountry,

    /**
     * The ModelsCoupon model constructor.
     * @property {module:model/ModelsCoupon}
     */
    ModelsCoupon,

    /**
     * The ModelsCouponOptions model constructor.
     * @property {module:model/ModelsCouponOptions}
     */
    ModelsCouponOptions,

    /**
     * The ModelsCreateMailReport model constructor.
     * @property {module:model/ModelsCreateMailReport}
     */
    ModelsCreateMailReport,

    /**
     * The ModelsDNSRecord model constructor.
     * @property {module:model/ModelsDNSRecord}
     */
    ModelsDNSRecord,

    /**
     * The ModelsDedicatedIPs model constructor.
     * @property {module:model/ModelsDedicatedIPs}
     */
    ModelsDedicatedIPs,

    /**
     * The ModelsDeleteResponse model constructor.
     * @property {module:model/ModelsDeleteResponse}
     */
    ModelsDeleteResponse,

    /**
     * The ModelsDetailedAlert model constructor.
     * @property {module:model/ModelsDetailedAlert}
     */
    ModelsDetailedAlert,

    /**
     * The ModelsDomain model constructor.
     * @property {module:model/ModelsDomain}
     */
    ModelsDomain,

    /**
     * The ModelsDomainAge model constructor.
     * @property {module:model/ModelsDomainAge}
     */
    ModelsDomainAge,

    /**
     * The ModelsDomainCheckResult model constructor.
     * @property {module:model/ModelsDomainCheckResult}
     */
    ModelsDomainCheckResult,

    /**
     * The ModelsEAccount model constructor.
     * @property {module:model/ModelsEAccount}
     */
    ModelsEAccount,

    /**
     * The ModelsEAccountMember model constructor.
     * @property {module:model/ModelsEAccountMember}
     */
    ModelsEAccountMember,

    /**
     * The ModelsEAccountSetting model constructor.
     * @property {module:model/ModelsEAccountSetting}
     */
    ModelsEAccountSetting,

    /**
     * The ModelsEAlert model constructor.
     * @property {module:model/ModelsEAlert}
     */
    ModelsEAlert,

    /**
     * The ModelsEComment model constructor.
     * @property {module:model/ModelsEComment}
     */
    ModelsEComment,

    /**
     * The ModelsEDomain model constructor.
     * @property {module:model/ModelsEDomain}
     */
    ModelsEDomain,

    /**
     * The ModelsEIP model constructor.
     * @property {module:model/ModelsEIP}
     */
    ModelsEIP,

    /**
     * The ModelsEIPPool model constructor.
     * @property {module:model/ModelsEIPPool}
     */
    ModelsEIPPool,

    /**
     * The ModelsEIncident model constructor.
     * @property {module:model/ModelsEIncident}
     */
    ModelsEIncident,

    /**
     * The ModelsEIntegration model constructor.
     * @property {module:model/ModelsEIntegration}
     */
    ModelsEIntegration,

    /**
     * The ModelsEInvitation model constructor.
     * @property {module:model/ModelsEInvitation}
     */
    ModelsEInvitation,

    /**
     * The ModelsEMember model constructor.
     * @property {module:model/ModelsEMember}
     */
    ModelsEMember,

    /**
     * The ModelsESender model constructor.
     * @property {module:model/ModelsESender}
     */
    ModelsESender,

    /**
     * The ModelsESubAccount model constructor.
     * @property {module:model/ModelsESubAccount}
     */
    ModelsESubAccount,

    /**
     * The ModelsESystemDomain model constructor.
     * @property {module:model/ModelsESystemDomain}
     */
    ModelsESystemDomain,

    /**
     * The ModelsEThirdPartySendingProvider model constructor.
     * @property {module:model/ModelsEThirdPartySendingProvider}
     */
    ModelsEThirdPartySendingProvider,

    /**
     * The ModelsEWebhook model constructor.
     * @property {module:model/ModelsEWebhook}
     */
    ModelsEWebhook,

    /**
     * The ModelsEditorTokenResponse model constructor.
     * @property {module:model/ModelsEditorTokenResponse}
     */
    ModelsEditorTokenResponse,

    /**
     * The ModelsEmailList model constructor.
     * @property {module:model/ModelsEmailList}
     */
    ModelsEmailList,

    /**
     * The ModelsEmailMessage model constructor.
     * @property {module:model/ModelsEmailMessage}
     */
    ModelsEmailMessage,

    /**
     * The ModelsEmailResponse model constructor.
     * @property {module:model/ModelsEmailResponse}
     */
    ModelsEmailResponse,

    /**
     * The ModelsEventMetadata model constructor.
     * @property {module:model/ModelsEventMetadata}
     */
    ModelsEventMetadata,

    /**
     * The ModelsFrom model constructor.
     * @property {module:model/ModelsFrom}
     */
    ModelsFrom,

    /**
     * The ModelsHetrixtoolsBlacklist model constructor.
     * @property {module:model/ModelsHetrixtoolsBlacklist}
     */
    ModelsHetrixtoolsBlacklist,

    /**
     * The ModelsHetrixtoolsMonitorStat model constructor.
     * @property {module:model/ModelsHetrixtoolsMonitorStat}
     */
    ModelsHetrixtoolsMonitorStat,

    /**
     * The ModelsIEIP model constructor.
     * @property {module:model/ModelsIEIP}
     */
    ModelsIEIP,

    /**
     * The ModelsIEMember model constructor.
     * @property {module:model/ModelsIEMember}
     */
    ModelsIEMember,

    /**
     * The ModelsIESubAccount model constructor.
     * @property {module:model/ModelsIESubAccount}
     */
    ModelsIESubAccount,

    /**
     * The ModelsIETag model constructor.
     * @property {module:model/ModelsIETag}
     */
    ModelsIETag,

    /**
     * The ModelsIIP model constructor.
     * @property {module:model/ModelsIIP}
     */
    ModelsIIP,

    /**
     * The ModelsIP model constructor.
     * @property {module:model/ModelsIP}
     */
    ModelsIP,

    /**
     * The ModelsIPDomainWarmupStatus model constructor.
     * @property {module:model/ModelsIPDomainWarmupStatus}
     */
    ModelsIPDomainWarmupStatus,

    /**
     * The ModelsIPHealthResponse model constructor.
     * @property {module:model/ModelsIPHealthResponse}
     */
    ModelsIPHealthResponse,

    /**
     * The ModelsIPPool model constructor.
     * @property {module:model/ModelsIPPool}
     */
    ModelsIPPool,

    /**
     * The ModelsIPProviderSettings model constructor.
     * @property {module:model/ModelsIPProviderSettings}
     */
    ModelsIPProviderSettings,

    /**
     * The ModelsIPStat model constructor.
     * @property {module:model/ModelsIPStat}
     */
    ModelsIPStat,

    /**
     * The ModelsIncident model constructor.
     * @property {module:model/ModelsIncident}
     */
    ModelsIncident,

    /**
     * The ModelsInstance model constructor.
     * @property {module:model/ModelsInstance}
     */
    ModelsInstance,

    /**
     * The ModelsIntegration model constructor.
     * @property {module:model/ModelsIntegration}
     */
    ModelsIntegration,

    /**
     * The ModelsIntegrationSettings model constructor.
     * @property {module:model/ModelsIntegrationSettings}
     */
    ModelsIntegrationSettings,

    /**
     * The ModelsInvitation model constructor.
     * @property {module:model/ModelsInvitation}
     */
    ModelsInvitation,

    /**
     * The ModelsLabel model constructor.
     * @property {module:model/ModelsLabel}
     */
    ModelsLabel,

    /**
     * The ModelsLinks model constructor.
     * @property {module:model/ModelsLinks}
     */
    ModelsLinks,

    /**
     * The ModelsMailReportResult model constructor.
     * @property {module:model/ModelsMailReportResult}
     */
    ModelsMailReportResult,

    /**
     * The ModelsMailgunClientInfo model constructor.
     * @property {module:model/ModelsMailgunClientInfo}
     */
    ModelsMailgunClientInfo,

    /**
     * The ModelsMailgunDeliveryStatus model constructor.
     * @property {module:model/ModelsMailgunDeliveryStatus}
     */
    ModelsMailgunDeliveryStatus,

    /**
     * The ModelsMailgunEvent model constructor.
     * @property {module:model/ModelsMailgunEvent}
     */
    ModelsMailgunEvent,

    /**
     * The ModelsMailgunMessage model constructor.
     * @property {module:model/ModelsMailgunMessage}
     */
    ModelsMailgunMessage,

    /**
     * The ModelsMailgunSignature model constructor.
     * @property {module:model/ModelsMailgunSignature}
     */
    ModelsMailgunSignature,

    /**
     * The ModelsMailgunUserVariables model constructor.
     * @property {module:model/ModelsMailgunUserVariables}
     */
    ModelsMailgunUserVariables,

    /**
     * The ModelsMember model constructor.
     * @property {module:model/ModelsMember}
     */
    ModelsMember,

    /**
     * The ModelsOnboardingChecklist model constructor.
     * @property {module:model/ModelsOnboardingChecklist}
     */
    ModelsOnboardingChecklist,

    /**
     * The ModelsPDStat model constructor.
     * @property {module:model/ModelsPDStat}
     */
    ModelsPDStat,

    /**
     * The ModelsPaymentAddress model constructor.
     * @property {module:model/ModelsPaymentAddress}
     */
    ModelsPaymentAddress,

    /**
     * The ModelsPaymentOptions model constructor.
     * @property {module:model/ModelsPaymentOptions}
     */
    ModelsPaymentOptions,

    /**
     * The ModelsPaymentStatus model constructor.
     * @property {module:model/ModelsPaymentStatus}
     */
    ModelsPaymentStatus,

    /**
     * The ModelsPostmasterDomainStat model constructor.
     * @property {module:model/ModelsPostmasterDomainStat}
     */
    ModelsPostmasterDomainStat,

    /**
     * The ModelsPricing model constructor.
     * @property {module:model/ModelsPricing}
     */
    ModelsPricing,

    /**
     * The ModelsProvider model constructor.
     * @property {module:model/ModelsProvider}
     */
    ModelsProvider,

    /**
     * The ModelsProviderDetails model constructor.
     * @property {module:model/ModelsProviderDetails}
     */
    ModelsProviderDetails,

    /**
     * The ModelsProviderResult model constructor.
     * @property {module:model/ModelsProviderResult}
     */
    ModelsProviderResult,

    /**
     * The ModelsProviderSettings model constructor.
     * @property {module:model/ModelsProviderSettings}
     */
    ModelsProviderSettings,

    /**
     * The ModelsQEmailMessage model constructor.
     * @property {module:model/ModelsQEmailMessage}
     */
    ModelsQEmailMessage,

    /**
     * The ModelsQEvent model constructor.
     * @property {module:model/ModelsQEvent}
     */
    ModelsQEvent,

    /**
     * The ModelsRAssumeAccount model constructor.
     * @property {module:model/ModelsRAssumeAccount}
     */
    ModelsRAssumeAccount,

    /**
     * The ModelsRDStat model constructor.
     * @property {module:model/ModelsRDStat}
     */
    ModelsRDStat,

    /**
     * The ModelsRDSuppression model constructor.
     * @property {module:model/ModelsRDSuppression}
     */
    ModelsRDSuppression,

    /**
     * The ModelsRHetrixtoolsMonitorStat model constructor.
     * @property {module:model/ModelsRHetrixtoolsMonitorStat}
     */
    ModelsRHetrixtoolsMonitorStat,

    /**
     * The ModelsRIPStat model constructor.
     * @property {module:model/ModelsRIPStat}
     */
    ModelsRIPStat,

    /**
     * The ModelsRStat model constructor.
     * @property {module:model/ModelsRStat}
     */
    ModelsRStat,

    /**
     * The ModelsRSuppression model constructor.
     * @property {module:model/ModelsRSuppression}
     */
    ModelsRSuppression,

    /**
     * The ModelsReplyTo model constructor.
     * @property {module:model/ModelsReplyTo}
     */
    ModelsReplyTo,

    /**
     * The ModelsReportProvider model constructor.
     * @property {module:model/ModelsReportProvider}
     */
    ModelsReportProvider,

    /**
     * The ModelsResponse model constructor.
     * @property {module:model/ModelsResponse}
     */
    ModelsResponse,

    /**
     * The ModelsSDStat model constructor.
     * @property {module:model/ModelsSDStat}
     */
    ModelsSDStat,

    /**
     * The ModelsSMTPAuth model constructor.
     * @property {module:model/ModelsSMTPAuth}
     */
    ModelsSMTPAuth,

    /**
     * The ModelsSMTPStat model constructor.
     * @property {module:model/ModelsSMTPStat}
     */
    ModelsSMTPStat,

    /**
     * The ModelsSSLCertificate model constructor.
     * @property {module:model/ModelsSSLCertificate}
     */
    ModelsSSLCertificate,

    /**
     * The ModelsSSLInfo model constructor.
     * @property {module:model/ModelsSSLInfo}
     */
    ModelsSSLInfo,

    /**
     * The ModelsSender model constructor.
     * @property {module:model/ModelsSender}
     */
    ModelsSender,

    /**
     * The ModelsSendgridEvent model constructor.
     * @property {module:model/ModelsSendgridEvent}
     */
    ModelsSendgridEvent,

    /**
     * The ModelsSingleCleanedMail model constructor.
     * @property {module:model/ModelsSingleCleanedMail}
     */
    ModelsSingleCleanedMail,

    /**
     * The ModelsStat model constructor.
     * @property {module:model/ModelsStat}
     */
    ModelsStat,

    /**
     * The ModelsSubAccount model constructor.
     * @property {module:model/ModelsSubAccount}
     */
    ModelsSubAccount,

    /**
     * The ModelsSuppression model constructor.
     * @property {module:model/ModelsSuppression}
     */
    ModelsSuppression,

    /**
     * The ModelsSuppressionEmail model constructor.
     * @property {module:model/ModelsSuppressionEmail}
     */
    ModelsSuppressionEmail,

    /**
     * The ModelsSystemDNSRecord model constructor.
     * @property {module:model/ModelsSystemDNSRecord}
     */
    ModelsSystemDNSRecord,

    /**
     * The ModelsSystemDomain model constructor.
     * @property {module:model/ModelsSystemDomain}
     */
    ModelsSystemDomain,

    /**
     * The ModelsSystemIPPool model constructor.
     * @property {module:model/ModelsSystemIPPool}
     */
    ModelsSystemIPPool,

    /**
     * The ModelsSystemTemplate model constructor.
     * @property {module:model/ModelsSystemTemplate}
     */
    ModelsSystemTemplate,

    /**
     * The ModelsTag model constructor.
     * @property {module:model/ModelsTag}
     */
    ModelsTag,

    /**
     * The ModelsTaxDetails model constructor.
     * @property {module:model/ModelsTaxDetails}
     */
    ModelsTaxDetails,

    /**
     * The ModelsThirdPartySendingProvider model constructor.
     * @property {module:model/ModelsThirdPartySendingProvider}
     */
    ModelsThirdPartySendingProvider,

    /**
     * The ModelsTo model constructor.
     * @property {module:model/ModelsTo}
     */
    ModelsTo,

    /**
     * The ModelsValidation model constructor.
     * @property {module:model/ModelsValidation}
     */
    ModelsValidation,

    /**
     * The ModelsVerifyByMemberTokenRequest model constructor.
     * @property {module:model/ModelsVerifyByMemberTokenRequest}
     */
    ModelsVerifyByMemberTokenRequest,

    /**
     * The ModelsVerifyByTokenRequest model constructor.
     * @property {module:model/ModelsVerifyByTokenRequest}
     */
    ModelsVerifyByTokenRequest,

    /**
     * The ModelsWMessage model constructor.
     * @property {module:model/ModelsWMessage}
     */
    ModelsWMessage,

    /**
     * The UaparserDevice model constructor.
     * @property {module:model/UaparserDevice}
     */
    UaparserDevice,

    /**
     * The UaparserOs model constructor.
     * @property {module:model/UaparserOs}
     */
    UaparserOs,

    /**
     * The UaparserUserAgent model constructor.
     * @property {module:model/UaparserUserAgent}
     */
    UaparserUserAgent,

    /**
    * The AccountAdminApi service constructor.
    * @property {module:api/AccountAdminApi}
    */
    AccountAdminApi,

    /**
    * The AccountAlertApi service constructor.
    * @property {module:api/AccountAlertApi}
    */
    AccountAlertApi,

    /**
    * The AccountDomainApi service constructor.
    * @property {module:api/AccountDomainApi}
    */
    AccountDomainApi,

    /**
    * The AccountDomainReportApi service constructor.
    * @property {module:api/AccountDomainReportApi}
    */
    AccountDomainReportApi,

    /**
    * The AccountDomainStatApi service constructor.
    * @property {module:api/AccountDomainStatApi}
    */
    AccountDomainStatApi,

    /**
    * The AccountEventApi service constructor.
    * @property {module:api/AccountEventApi}
    */
    AccountEventApi,

    /**
    * The AccountIncidentApi service constructor.
    * @property {module:api/AccountIncidentApi}
    */
    AccountIncidentApi,

    /**
    * The AccountIntegrationApi service constructor.
    * @property {module:api/AccountIntegrationApi}
    */
    AccountIntegrationApi,

    /**
    * The AccountInvitationApi service constructor.
    * @property {module:api/AccountInvitationApi}
    */
    AccountInvitationApi,

    /**
    * The AccountIpApi service constructor.
    * @property {module:api/AccountIpApi}
    */
    AccountIpApi,

    /**
    * The AccountIpStatApi service constructor.
    * @property {module:api/AccountIpStatApi}
    */
    AccountIpStatApi,

    /**
    * The AccountIppoolApi service constructor.
    * @property {module:api/AccountIppoolApi}
    */
    AccountIppoolApi,

    /**
    * The AccountLabelApi service constructor.
    * @property {module:api/AccountLabelApi}
    */
    AccountLabelApi,

    /**
    * The AccountMailReportApi service constructor.
    * @property {module:api/AccountMailReportApi}
    */
    AccountMailReportApi,

    /**
    * The AccountMemberApi service constructor.
    * @property {module:api/AccountMemberApi}
    */
    AccountMemberApi,

    /**
    * The AccountMessageApi service constructor.
    * @property {module:api/AccountMessageApi}
    */
    AccountMessageApi,

    /**
    * The AccountOnboardingApi service constructor.
    * @property {module:api/AccountOnboardingApi}
    */
    AccountOnboardingApi,

    /**
    * The AccountPaymentApi service constructor.
    * @property {module:api/AccountPaymentApi}
    */
    AccountPaymentApi,

    /**
    * The AccountRecipientApi service constructor.
    * @property {module:api/AccountRecipientApi}
    */
    AccountRecipientApi,

    /**
    * The AccountSettingApi service constructor.
    * @property {module:api/AccountSettingApi}
    */
    AccountSettingApi,

    /**
    * The AccountSmtpStatApi service constructor.
    * @property {module:api/AccountSmtpStatApi}
    */
    AccountSmtpStatApi,

    /**
    * The AccountStatApi service constructor.
    * @property {module:api/AccountStatApi}
    */
    AccountStatApi,

    /**
    * The AccountSubaccountApi service constructor.
    * @property {module:api/AccountSubaccountApi}
    */
    AccountSubaccountApi,

    /**
    * The AccountSubaccountStatApi service constructor.
    * @property {module:api/AccountSubaccountStatApi}
    */
    AccountSubaccountStatApi,

    /**
    * The AccountTagApi service constructor.
    * @property {module:api/AccountTagApi}
    */
    AccountTagApi,

    /**
    * The AccountTemplateApi service constructor.
    * @property {module:api/AccountTemplateApi}
    */
    AccountTemplateApi,

    /**
    * The AccountTpspApi service constructor.
    * @property {module:api/AccountTpspApi}
    */
    AccountTpspApi,

    /**
    * The AccountTpspStatApi service constructor.
    * @property {module:api/AccountTpspStatApi}
    */
    AccountTpspStatApi,

    /**
    * The AccountValidationApi service constructor.
    * @property {module:api/AccountValidationApi}
    */
    AccountValidationApi,

    /**
    * The AccountWebhookApi service constructor.
    * @property {module:api/AccountWebhookApi}
    */
    AccountWebhookApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The ClusterApi service constructor.
    * @property {module:api/ClusterApi}
    */
    ClusterApi,

    /**
    * The EditorApi service constructor.
    * @property {module:api/EditorApi}
    */
    EditorApi,

    /**
    * The SmtpApi service constructor.
    * @property {module:api/SmtpApi}
    */
    SmtpApi,

    /**
    * The SubaccountDomainApi service constructor.
    * @property {module:api/SubaccountDomainApi}
    */
    SubaccountDomainApi,

    /**
    * The SubaccountEmailApi service constructor.
    * @property {module:api/SubaccountEmailApi}
    */
    SubaccountEmailApi,

    /**
    * The SubaccountIppoolApi service constructor.
    * @property {module:api/SubaccountIppoolApi}
    */
    SubaccountIppoolApi,

    /**
    * The SubaccountSenderApi service constructor.
    * @property {module:api/SubaccountSenderApi}
    */
    SubaccountSenderApi,

    /**
    * The SubaccountSuppressionApi service constructor.
    * @property {module:api/SubaccountSuppressionApi}
    */
    SubaccountSuppressionApi,

    /**
    * The SystemSuppressionApi service constructor.
    * @property {module:api/SystemSuppressionApi}
    */
    SystemSuppressionApi,

    /**
    * The SystemTemplateApi service constructor.
    * @property {module:api/SystemTemplateApi}
    */
    SystemTemplateApi,

    /**
    * The TrackApi service constructor.
    * @property {module:api/TrackApi}
    */
    TrackApi
};
