/*
 * SendPost API
 * Email API and SMTP relay to not just send and measure email sending, but also alert and optimise. We provide you with tools, expertise and support needed to reliably deliver emails to your customers inboxes on time, every time. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendpost.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendPostApi);
  }
}(this, function(expect, SendPostApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendPostApi.AccountcustomerPortalApi();
  });

  describe('(package)', function() {
    describe('AccountcustomerPortalApi', function() {
      describe('customerPortalRouterCreateTicketWithAssContactAndCompany', function() {
        it('should call customerPortalRouterCreateTicketWithAssContactAndCompany successfully', function(done) {
          // TODO: uncomment, update parameter values for customerPortalRouterCreateTicketWithAssContactAndCompany call
          /*
          var xAccountApiKey = "xAccountApiKey_example";
          var memberId = 789;
          var body = new SendPostApi.ModelsRequestCreateTicket();
          body.attachmentId = "";
          body.attachmentUrl = "";
          body.category = "";
          body.content = "";
          body.subject = "";

          instance.customerPortalRouterCreateTicketWithAssContactAndCompany(xAccountApiKey, memberId, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('customerPortalRouterGetCompanyTickets', function() {
        it('should call customerPortalRouterGetCompanyTickets successfully', function(done) {
          // TODO: uncomment, update parameter values for customerPortalRouterGetCompanyTickets call and complete the assertions
          /*
          var xAccountApiKey = "xAccountApiKey_example";

          instance.customerPortalRouterGetCompanyTickets(xAccountApiKey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SendPostApi.ModelsHubspotTicket);
              {
                let dataCtr = data.emails;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(SendPostApi.ModelsHubspotEmail);
                  expect(data.properties).to.be.a(SendPostApi.ModelsHubspotEmailProperties);
                        expect(data.properties.hsCreatedate).to.be.a('string');
                    expect(data.properties.hsCreatedate).to.be("");
                    expect(data.properties.hsEmailFromEmail).to.be.a('string');
                    expect(data.properties.hsEmailFromEmail).to.be("");
                    expect(data.properties.hsEmailSubject).to.be.a('string');
                    expect(data.properties.hsEmailSubject).to.be("");
                    expect(data.properties.hsEmailText).to.be.a('string');
                    expect(data.properties.hsEmailText).to.be("");
                    expect(data.properties.hsLastmodifieddate).to.be.a('string');
                    expect(data.properties.hsLastmodifieddate).to.be("");
  
                        }
              }
              expect(data.id).to.be.a('string');
              expect(data.id).to.be("");
              expect(data.properties).to.be.a(SendPostApi.ModelsHubspotTicketProperties);
                    expect(data.properties.content).to.be.a('string');
                expect(data.properties.content).to.be("");
                expect(data.properties.createdate).to.be.a('string');
                expect(data.properties.createdate).to.be("");
                expect(data.properties.hsPipeline).to.be.a('string');
                expect(data.properties.hsPipeline).to.be("");
                expect(data.properties.hsPipelineStage).to.be.a('string');
                expect(data.properties.hsPipelineStage).to.be("");
                expect(data.properties.hsTicketCategory).to.be.a('string');
                expect(data.properties.hsTicketCategory).to.be("");
                expect(data.properties.hsTicketPriority).to.be.a('string');
                expect(data.properties.hsTicketPriority).to.be("");
                expect(data.properties.linearIssue).to.be.a('string');
                expect(data.properties.linearIssue).to.be("");
                expect(data.properties.linearUuid).to.be.a('string');
                expect(data.properties.linearUuid).to.be("");
                expect(data.properties.subject).to.be.a('string');
                expect(data.properties.subject).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('customerPortalRouterGetTicketDetails', function() {
        it('should call customerPortalRouterGetTicketDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for customerPortalRouterGetTicketDetails call and complete the assertions
          /*
          var xAccountApiKey = "xAccountApiKey_example";
          var id = 789;

          instance.customerPortalRouterGetTicketDetails(xAccountApiKey, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendPostApi.ModelsHubspotTicket);
            {
              let dataCtr = data.emails;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SendPostApi.ModelsHubspotEmail);
                expect(data.properties).to.be.a(SendPostApi.ModelsHubspotEmailProperties);
                      expect(data.properties.hsCreatedate).to.be.a('string');
                  expect(data.properties.hsCreatedate).to.be("");
                  expect(data.properties.hsEmailFromEmail).to.be.a('string');
                  expect(data.properties.hsEmailFromEmail).to.be("");
                  expect(data.properties.hsEmailSubject).to.be.a('string');
                  expect(data.properties.hsEmailSubject).to.be("");
                  expect(data.properties.hsEmailText).to.be.a('string');
                  expect(data.properties.hsEmailText).to.be("");
                  expect(data.properties.hsLastmodifieddate).to.be.a('string');
                  expect(data.properties.hsLastmodifieddate).to.be("");

                      }
            }
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.properties).to.be.a(SendPostApi.ModelsHubspotTicketProperties);
                  expect(data.properties.content).to.be.a('string');
              expect(data.properties.content).to.be("");
              expect(data.properties.createdate).to.be.a('string');
              expect(data.properties.createdate).to.be("");
              expect(data.properties.hsPipeline).to.be.a('string');
              expect(data.properties.hsPipeline).to.be("");
              expect(data.properties.hsPipelineStage).to.be.a('string');
              expect(data.properties.hsPipelineStage).to.be("");
              expect(data.properties.hsTicketCategory).to.be.a('string');
              expect(data.properties.hsTicketCategory).to.be("");
              expect(data.properties.hsTicketPriority).to.be.a('string');
              expect(data.properties.hsTicketPriority).to.be("");
              expect(data.properties.linearIssue).to.be.a('string');
              expect(data.properties.linearIssue).to.be("");
              expect(data.properties.linearUuid).to.be.a('string');
              expect(data.properties.linearUuid).to.be("");
              expect(data.properties.subject).to.be.a('string');
              expect(data.properties.subject).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('customerPortalRouterUploadFileToHubspot', function() {
        it('should call customerPortalRouterUploadFileToHubspot successfully', function(done) {
          // TODO: uncomment, update parameter values for customerPortalRouterUploadFileToHubspot call and complete the assertions
          /*
          var file = "/path/to/file.txt";
          var xAccountApiKey = "xAccountApiKey_example";

          instance.customerPortalRouterUploadFileToHubspot(file, xAccountApiKey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendPostApi.ModelsUploadFileResponse);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
