/*
 * SendPost API
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendPostApi);
  }
}(this, function(expect, SendPostApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendPostApi.SubaccountcleanlistApi();
  });

  describe('(package)', function() {
    describe('SubaccountcleanlistApi', function() {
      describe('listCleaningRouterCleanBulkEmailList', function() {
        it('should call listCleaningRouterCleanBulkEmailList successfully', function(done) {
          // TODO: uncomment, update parameter values for listCleaningRouterCleanBulkEmailList call and complete the assertions
          /*
          var fileinput = "/path/to/file.txt";
          var xSubAccountApiKey = "xSubAccountApiKey_example";

          instance.listCleaningRouterCleanBulkEmailList(fileinput, xSubAccountApiKey, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendPostApi.ModelsBulkResponse);
            expect(data.jobId).to.be.a('number');
            expect(data.jobId).to.be("0");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listCleaningRouterCleanEmailist', function() {
        it('should call listCleaningRouterCleanEmailist successfully', function(done) {
          // TODO: uncomment, update parameter values for listCleaningRouterCleanEmailist call and complete the assertions
          /*
          var xSubAccountApiKey = "xSubAccountApiKey_example";
          var body = new SendPostApi.ModelsEmailList();
          body.emailIds = ;

          instance.listCleaningRouterCleanEmailist(xSubAccountApiKey, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendPostApi.ModelsCleanedList);
            {
              let dataCtr = data.detailedResponse;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SendPostApi.ModelsSingleCleanedMail);
                expect(data.err).to.be.a('string');
                expect(data.err).to.be("");
                expect(data.mailId).to.be.a('string');
                expect(data.mailId).to.be("");
                expect(data.reason).to.be.a('string');
                expect(data.reason).to.be("");
                expect(data.valid).to.be.a('boolean');
                expect(data.valid).to.be(false);

                      }
            }
            expect(data.invalid).to.be.a(Object);
            expect(data.invalid).to.be();
            expect(data.valid).to.be.a(Object);
            expect(data.valid).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
